(()=>{
const app=document.body.dataset.app;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=async(path,options={})=>{const o={credentials:'same-origin',...options,headers:{'content-type':'application/json',...(options.headers||{})}};if(o.body&&typeof o.body!=='string')o.body=JSON.stringify(o.body);const r=await fetch('/api/'+path,o);let d;try{d=await r.json()}catch{d={ok:false,error:'Invalid server response'}}if(!r.ok)throw Object.assign(new Error(d.error||'Request failed'),{status:r.status,data:d});return d;};
const msg=(el,text,type='')=>{if(!el)return;el.innerHTML=text?`<div class="notice ${type==='good'?'good':''}">${esc(text)}</div>`:'';};
const formObj=form=>Object.fromEntries(new FormData(form).entries());
const statusBadge=s=>`<span class="badge ${esc(s)}">${esc(String(s).replace('_',' '))}</span>`;
const fmtDate=d=>{try{return new Intl.DateTimeFormat('en-IN',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T00:00:00'))}catch{return d}};
const dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
let me=null, services=[], therapists=[], settings={};
async function who(){try{const d=await api('auth/me');me=d.user;return me}catch{return null}}
async function loadServices(publicOnly=true){const d=await api(publicOnly?'public/services':'admin/services');services=d.services||[];return services}
async function loadTherapists(publicOnly=false,serviceId=null){const path=publicOnly?'public/therapists'+(serviceId?`?service_id=${serviceId}`:''):'admin/therapists';const d=await api(path);therapists=d.therapists||[];return therapists}
async function logout(){try{await api('auth/logout',{method:'POST',body:{}})}catch{}location.href='portal.html'}

async function initPortal(){
 const authView=$('#auth-view'), portalView=$('#portal-view'), authMessage=$('#auth-message'), apiNotice=$('#api-notice');
 try{await api('health')}catch(e){if(e.status===503)msg(apiNotice,'The V2 portal code is deployed, but the Cloudflare D1 database still needs to be connected. Complete the D1 setup in Cloudflare, then refresh this page.');}
 $$('[data-auth-tab]').forEach(b=>b.onclick=()=>{$$('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.auth-form').forEach(f=>f.classList.toggle('active',f.id.startsWith(b.dataset.authTab)))});
 $('#login-form').onsubmit=async e=>{e.preventDefault();msg(authMessage,'');const d=formObj(e.target);try{await api('auth/login',{method:'POST',body:d});location.reload()}catch(x){msg(authMessage,x.message)}};
 $('#signup-form').onsubmit=async e=>{e.preventDefault();msg(authMessage,'');const d=formObj(e.target);try{await api('auth/signup',{method:'POST',body:d});location.reload()}catch(x){msg(authMessage,x.message)}};
 me=await who(); if(!me)return;
 authView.classList.add('hidden');portalView.classList.remove('hidden');$('#portal-user').textContent=`${me.name} · ${me.role}`;$('#logout-btn').onclick=logout;
 if(['admin','super_admin'].includes(me.role)){const l=$('#staff-link');l.classList.remove('hidden');l.href='admin.html';l.textContent='Admin dashboard';}
 else if(me.role==='therapist'){const l=$('#staff-link');l.classList.remove('hidden');l.href='therapist.html';l.textContent='Therapist portal';}
 $('#toggle-patient-form').onclick=()=>$('#patient-form-wrap').classList.toggle('hidden');
 $('#patient-form').onsubmit=async e=>{e.preventDefault();try{await api('patients',{method:'POST',body:formObj(e.target)});e.target.reset();$('#patient-form-wrap').classList.add('hidden');await loadPatients();msg($('#portal-message'),'Profile saved.','good')}catch(x){msg($('#portal-message'),x.message)}};
 $('#refresh-appts').onclick=loadAppointments;
 await Promise.all([loadPatients(),loadBookingServices(),loadAppointments()]);
 $('#book-service').onchange=async()=>{await populateTherapists();await loadSlots()};$('#book-therapist').onchange=loadSlots;$('#book-date').onchange=loadSlots;
 $('#booking-form').onsubmit=async e=>{e.preventDefault();const d=formObj(e.target);if(!d.start)return msg($('#portal-message'),'Please choose an available slot.');try{await api('appointments',{method:'POST',body:d});msg($('#portal-message'),'Appointment requested. The center can now review and confirm it.','good');$('#book-start').value='';await Promise.all([loadSlots(),loadAppointments()])}catch(x){msg($('#portal-message'),x.message)}};
 async function loadPatients(){try{const d=await api('patients');const rows=d.patients||[];$('#patients-list').innerHTML=rows.length?rows.map(p=>`<div class="patient-card"><strong>${esc(p.name)}</strong><div class="muted">${esc(p.relationship||'Client')}${p.date_of_birth?' · DOB '+esc(p.date_of_birth):''}</div></div>`).join(''):'<div class="empty">Add a child or client profile before booking.</div>';$('#book-patient').innerHTML='<option value="">Choose profile</option>'+rows.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}catch(x){msg($('#portal-message'),x.message)}}
 async function loadBookingServices(){try{await loadServices(true);$('#book-service').innerHTML='<option value="">Choose service</option>'+services.map(s=>`<option value="${s.id}">${esc(s.title)} · ${s.duration_minutes} min</option>`).join('')}catch(x){msg($('#portal-message'),x.message)}}
 async function populateTherapists(){const sid=$('#book-service').value;$('#book-therapist').innerHTML='<option value="">Any available therapist</option>';if(!sid)return;try{const d=await api(`public/therapists?service_id=${sid}`);$('#book-therapist').innerHTML+=[...(d.therapists||[])].map(t=>`<option value="${t.id}">${esc(t.name)}${t.title?' · '+esc(t.title):''}</option>`).join('')}catch{}}
 async function loadSlots(){const sid=$('#book-service').value,date=$('#book-date').value,tid=$('#book-therapist').value;$('#book-start').value='';const grid=$('#slot-grid');if(!sid||!date){grid.innerHTML='';return}grid.innerHTML='<span class="spinner"></span>';try{const d=await api(`public/slots?service_id=${sid}&date=${date}${tid?'&therapist_id='+tid:''}`);const slots=d.slots||[];$('#slot-help').textContent=slots.length?'Choose one available time.':'No open slots are currently configured for this date.';grid.innerHTML=slots.map(s=>`<button type="button" class="slot" data-start="${s.start}" data-therapist="${s.therapist_id}">${esc(s.start)}<small>${esc(s.therapist_name)} · ${s.duration_minutes} min</small></button>`).join('');$$('.slot',grid).forEach(b=>b.onclick=()=>{$$('.slot',grid).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#book-start').value=b.dataset.start;$('#book-therapist').value=b.dataset.therapist})}catch(x){grid.innerHTML='';msg($('#portal-message'),x.message)}}
 async function loadAppointments(){try{const d=await api('appointments');const rows=d.appointments||[];$('#appointments-list').innerHTML=rows.length?rows.map(a=>`<div class="appt-card"><div class="toolbar"><strong>${esc(a.service_title)}</strong>${statusBadge(a.status)}<span class="right muted">${fmtDate(a.appointment_date)}</span></div><div style="margin-top:8px">${esc(a.start_time)}–${esc(a.end_time)} · ${esc(a.therapist_name)} · ${esc(a.mode)}</div><div class="muted">For ${esc(a.patient_name)}</div>${['pending','confirmed'].includes(a.status)?`<div class="toolbar" style="margin-top:10px"><button class="btn btn-danger btn-sm" data-cancel="${a.id}">Cancel</button></div>`:''}</div>`).join(''):'<div class="empty">No appointments yet.</div>';$$('[data-cancel]').forEach(b=>b.onclick=async()=>{if(!confirm('Cancel this appointment?'))return;try{await api(`appointments/${b.dataset.cancel}/cancel`,{method:'POST',body:{}});await loadAppointments()}catch(x){msg($('#portal-message'),x.message)}})}catch(x){msg($('#portal-message'),x.message)}}
}

async function ensureRole(roles,redirect='portal.html'){me=await who();if(!me||!roles.includes(me.role)){location.href=redirect;return false}return true}
function navViews(){$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));function showView(name){$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('[data-view-panel]').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===name));const active=$(`[data-view="${name}"]`);$('#admin-title').textContent=active?active.textContent.trim():name;$('#app-side').classList.remove('open')}}

async function initAdmin(){
 if(!await ensureRole(['admin','super_admin']))return;navViews();$('#admin-name').textContent=me.name;$('#admin-role').textContent=me.role;$('#admin-avatar').textContent=(me.name||'E')[0].toUpperCase();$('#admin-logout').onclick=logout;$('#side-toggle').onclick=()=>$('#app-side').classList.toggle('open');
 $('#refresh-dashboard').onclick=loadDashboard;$('#refresh-admin-appts').onclick=loadAdminAppointments;$('#refresh-families').onclick=loadFamilies;
 await Promise.all([loadDashboard(),loadAdminAppointments(),loadFamilies(),loadAdminServices(),loadAdminTherapists(),loadAdminSettings(),loadContent(),loadClosures()]);
 $('#service-form').onsubmit=saveService;$('#closure-form').onsubmit=saveClosure;$('#booking-rules-form').onsubmit=saveBookingRules;$('#therapist-form').onsubmit=saveTherapist;$('#availability-therapist').onchange=loadAvailability;$('#availability-form').onsubmit=e=>saveAvailability(e,false);$('#block-form').onsubmit=e=>saveAvailability(e,true);$('#theme-form').onsubmit=saveTheme;$('#content-settings-form').onsubmit=saveVisibility;$('#hours-form').onsubmit=saveHours;$('#content-item-form').onsubmit=saveContent;
 $$('.theme-swatch').forEach(b=>b.onclick=()=>{const [p,a,i]=b.dataset.theme.split('|');const f=$('#theme-form');f.primary_color.value=p;f.accent_color.value=a;f.ink_color.value=i});
 async function loadDashboard(){try{const d=await api('admin/dashboard');const s=d.stats;$('#metrics').innerHTML=[['Today',s.today],['Upcoming',s.upcoming],['Pending',s.pending],['Families',s.parents],['Therapists',s.therapists]].map(([k,v])=>`<div class="metric"><span>${k}</span><b>${v}</b></div>`).join('')}catch(x){msg($('#admin-message'),x.message)}}
 async function loadAdminAppointments(){try{const d=await api('admin/appointments');const rows=d.appointments||[];$('#admin-appts').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Date</th><th>Time</th><th>Patient</th><th>Service</th><th>Therapist</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(a=>`<tr><td>${fmtDate(a.appointment_date)}</td><td>${esc(a.start_time)}</td><td><strong>${esc(a.patient_name)}</strong><br><small>${esc(a.parent_name||'')} ${esc(a.parent_phone||'')}</small></td><td>${esc(a.service_title)}</td><td>${esc(a.therapist_name)}</td><td>${statusBadge(a.status)}</td><td><select data-appt-status="${a.id}"><option value="pending" ${a.status==='pending'?'selected':''}>Pending</option><option value="confirmed" ${a.status==='confirmed'?'selected':''}>Confirmed</option><option value="completed" ${a.status==='completed'?'selected':''}>Completed</option><option value="cancelled" ${a.status==='cancelled'?'selected':''}>Cancelled</option><option value="no_show" ${a.status==='no_show'?'selected':''}>No show</option></select></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No appointments yet.</div>';$$('[data-appt-status]').forEach(s=>s.onchange=async()=>{try{await api('admin/appointments',{method:'POST',body:{id:s.dataset.apptStatus,status:s.value}});await loadDashboard();msg($('#admin-message'),'Appointment updated.','good')}catch(x){msg($('#admin-message'),x.message)}})}catch(x){msg($('#admin-message'),x.message)}}
 async function loadFamilies(){try{const d=await api('admin/families');const rows=d.families||[];$('#families-list').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Client</th><th>Parent / account</th><th>Contact</th><th>Relationship</th><th>Appointments</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.patient_name)}</strong>${x.date_of_birth?`<br><small>DOB ${esc(x.date_of_birth)}</small>`:''}</td><td>${esc(x.parent_name)}</td><td>${esc(x.parent_phone||'')}<br><small>${esc(x.parent_email||'')}</small></td><td>${esc(x.relationship||'')}</td><td>${x.appointment_count}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No parent/client profiles yet.</div>'}catch(x){msg($('#admin-message'),x.message)}}
 async function loadAdminServices(){try{await loadServices(false);$('#services-list').innerHTML=services.map(s=>`<button type="button" class="patient-card" style="text-align:left;cursor:pointer" data-edit-service="${s.id}"><strong>${esc(s.title)}</strong><div class="muted">${s.duration_minutes} min · ${esc(s.mode)} · ${s.active?'Active':'Hidden'}</div></button>`).join('');$('#therapist-service-checks').innerHTML=services.map(s=>`<label style="font-weight:600"><input type="checkbox" name="service_ids" value="${s.id}" style="width:auto"> ${esc(s.title)}</label>`).join('');$$('[data-edit-service]').forEach(b=>b.onclick=()=>{const s=services.find(x=>x.id==b.dataset.editService),f=$('#service-form');f.id.value=s.id;f.title.value=s.title;f.duration_minutes.value=s.duration_minutes;f.mode.value=s.mode;f.summary.value=s.summary||'';f.scrollIntoView({behavior:'smooth'})})}catch(x){msg($('#admin-message'),x.message)}}
 async function saveService(e){e.preventDefault();const d=formObj(e.target);d.id=d.id?Number(d.id):null;d.duration_minutes=Number(d.duration_minutes);try{await api('admin/services',{method:'POST',body:d});e.target.reset();await loadAdminServices();msg($('#admin-message'),'Service saved.','good')}catch(x){msg($('#admin-message'),x.message)}}
 async function loadAdminTherapists(){try{await loadTherapists(false);$('#therapists-list').innerHTML=therapists.length?therapists.map(t=>`<button type="button" class="patient-card" style="text-align:left;cursor:pointer" data-edit-therapist="${t.id}"><strong>${esc(t.name)}</strong><div class="muted">${esc(t.title||'Therapist')} · ${t.active?'Active':'Inactive'}</div><small>${esc(t.email||'')}</small></button>`).join(''):'<div class="empty">Add the first therapist to enable bookable slots.</div>';$('#availability-therapist').innerHTML='<option value="">Choose therapist</option>'+therapists.filter(t=>t.active).map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');$$('[data-edit-therapist]').forEach(b=>b.onclick=()=>{const t=therapists.find(x=>x.id==b.dataset.editTherapist),f=$('#therapist-form');for(const k of ['id','name','title','email','phone','qualifications','bio'])if(f[k])f[k].value=t[k]||'';const ids=String(t.service_ids||'').split(',');$$('input[name="service_ids"]',f).forEach(c=>c.checked=ids.includes(c.value));f.scrollIntoView({behavior:'smooth'})})}catch(x){msg($('#admin-message'),x.message)}}
 async function saveTherapist(e){e.preventDefault();const d=formObj(e.target);d.id=d.id?Number(d.id):null;d.service_ids=$$('input[name="service_ids"]',e.target).filter(x=>x.checked).map(x=>Number(x.value));try{await api('admin/therapists',{method:'POST',body:d});e.target.reset();await loadAdminTherapists();msg($('#admin-message'),'Therapist saved. If the therapist signs up using the same email, the account is automatically linked.','good')}catch(x){msg($('#admin-message'),x.message)}}
 async function loadAvailability(){const id=$('#availability-therapist').value;if(!id){$('#availability-list').innerHTML='';$('#blocks-list').innerHTML='';return}try{const d=await api(`therapist/availability?therapist_id=${id}`);$('#availability-list').innerHTML=(d.availability||[]).map(a=>`<div class="patient-card"><strong>${dayNames[a.weekday]}</strong><div>${esc(a.start_time)}–${esc(a.end_time)}</div></div>`).join('')||'<div class="empty">No weekly availability yet.</div>';$('#blocks-list').innerHTML=(d.blocks||[]).map(a=>`<div class="patient-card"><strong>${fmtDate(a.date)}</strong><div>${esc(a.start_time)}–${esc(a.end_time)} · ${esc(a.reason||'Unavailable')}</div></div>`).join('')||'<div class="empty">No future blocks.</div>'}catch(x){msg($('#admin-message'),x.message)}}
 async function saveAvailability(e,block){e.preventDefault();const id=$('#availability-therapist').value;if(!id)return msg($('#admin-message'),'Choose a therapist first.');const d=formObj(e.target);if(block)d.action='block';try{await api(`therapist/availability?therapist_id=${id}`,{method:'POST',body:d});await loadAvailability();msg($('#admin-message'),block?'Blocked time saved.':'Availability window added.','good')}catch(x){msg($('#admin-message'),x.message)}}
 async function loadClosures(){try{const d=await api('admin/closures');$('#closures-list').innerHTML=(d.closures||[]).map(x=>`<div class="patient-card"><div class="toolbar"><strong>${fmtDate(x.date)}</strong><span>${esc(x.reason||'Center closed')}</span><button class="btn btn-danger btn-sm right" data-delete-closure="${x.id}">Remove</button></div></div>`).join('')||'<div class="empty">No future center closures.</div>';$$('[data-delete-closure]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this center closure?'))return;try{await api('admin/closures',{method:'POST',body:{action:'delete',id:b.dataset.deleteClosure}});await loadClosures()}catch(x){msg($('#admin-message'),x.message)}})}catch(x){msg($('#admin-message'),x.message)}}
 async function saveClosure(e){e.preventDefault();try{await api('admin/closures',{method:'POST',body:formObj(e.target)});e.target.reset();await loadClosures();msg($('#admin-message'),'Center closure saved. No appointments will be offered on that date.','good')}catch(x){msg($('#admin-message'),x.message)}}
 async function loadAdminSettings(){try{const d=await api('admin/settings');settings=d.settings||{};const tf=$('#theme-form');for(const k of ['primary_color','accent_color','ink_color','card_radius','hero_style'])if(tf[k])tf[k].value=settings[k]||tf[k].value;const cf=$('#content-settings-form');for(const k of ['announcement_text','announcement_enabled','show_gallery','show_testimonials','show_programs'])if(cf[k])cf[k].value=settings[k]??'';const bf=$('#booking-rules-form');for(const k of ['slot_interval_minutes','booking_lead_minutes','booking_horizon_days'])if(bf?.[k])bf[k].value=settings[k]??bf[k].value;renderHours()}catch(x){msg($('#admin-message'),x.message)}}
 async function saveBookingRules(e){e.preventDefault();try{await api('admin/settings',{method:'POST',body:{settings:formObj(e.target)}});msg($('#admin-message'),'Booking rules saved. New slot searches use these values immediately.','good')}catch(x){msg($('#admin-message'),x.message)}}
 async function saveTheme(e){e.preventDefault();try{await api('admin/settings',{method:'POST',body:{settings:formObj(e.target)}});msg($('#admin-message'),'Theme saved. Public pages will use the new theme on refresh.','good')}catch(x){msg($('#admin-message'),x.message)}}
 async function saveVisibility(e){e.preventDefault();try{await api('admin/settings',{method:'POST',body:{settings:formObj(e.target)}});msg($('#admin-message'),'Website display settings saved.','good')}catch(x){msg($('#admin-message'),x.message)}}
 function renderHours(){let h={};try{h=JSON.parse(settings.business_hours||'{}')}catch{};$('#hours-grid').innerHTML=dayNames.map((name,i)=>{const v=h[i];return `<div class="day-grid"><strong class="day-label">${name}</strong><input type="time" name="h${i}s" value="${v?v[0]:''}" ${v?'':'disabled'}><input type="time" name="h${i}e" value="${v?v[1]:''}" ${v?'':'disabled'}><label style="font-weight:600"><input type="checkbox" data-day-open="${i}" ${v?'checked':''} style="width:auto"> Open</label></div>`}).join('');$$('[data-day-open]').forEach(c=>c.onchange=()=>{const row=c.closest('.day-grid');$$('input[type=time]',row).forEach(x=>{x.disabled=!c.checked;if(c.checked&&!x.value)x.value=x===row.querySelector('input[type=time]')?'09:30':'20:00'})})}
 async function saveHours(e){e.preventDefault();const h={};for(let i=0;i<7;i++){const c=$(`[data-day-open="${i}"]`);h[i]=c.checked?[e.target[`h${i}s`].value,e.target[`h${i}e`].value]:null}try{await api('admin/settings',{method:'POST',body:{settings:{business_hours:h}}});settings.business_hours=JSON.stringify(h);msg($('#admin-message'),'Clinic display hours saved.','good')}catch(x){msg($('#admin-message'),x.message)}}
 async function loadContent(){try{const d=await api('admin/content');$('#content-list').innerHTML=(d.items||[]).map(x=>`<div class="patient-card"><div class="toolbar"><strong>${esc(x.title||x.type)}</strong><span class="badge">${esc(x.type)}</span></div><div class="muted">${esc(x.body||'')}</div></div>`).join('')||'<div class="empty">No managed content items yet.</div>'}catch(x){if(x.status!==403)msg($('#admin-message'),x.message)}}
 async function saveContent(e){e.preventDefault();try{await api('admin/content',{method:'POST',body:formObj(e.target)});e.target.reset();await loadContent();msg($('#admin-message'),'Content item saved.','good')}catch(x){msg($('#admin-message'),x.message)}}
}

async function initTherapist(){
 if(!await ensureRole(['therapist','admin','super_admin']))return;$('#therapist-user').textContent=`${me.name} · ${me.role}`;$('#therapist-logout').onclick=logout;$('#refresh-schedule').onclick=loadSchedule;$('#therapist-availability-form').onsubmit=e=>save(e,false);$('#therapist-block-form').onsubmit=e=>save(e,true);await Promise.all([loadSchedule(),loadAvail()]);
 async function loadSchedule(){try{const d=await api('therapist/schedule');$('#therapist-schedule').innerHTML=(d.appointments||[]).map(a=>`<div class="appt-card"><div class="toolbar"><strong>${esc(a.patient_name)}</strong>${statusBadge(a.status)}<span class="right">${fmtDate(a.appointment_date)}</span></div><div>${esc(a.start_time)}–${esc(a.end_time)} · ${esc(a.service_title)} · ${esc(a.mode)}</div><div class="toolbar" style="margin-top:10px">${a.status==='pending'?`<button class="btn btn-secondary btn-sm" data-tstatus="confirmed" data-id="${a.id}">Confirm</button>`:''}${['pending','confirmed'].includes(a.status)?`<button class="btn btn-primary btn-sm" data-tstatus="completed" data-id="${a.id}">Complete</button><button class="btn btn-secondary btn-sm" data-tstatus="no_show" data-id="${a.id}">No show</button>`:''}</div></div>`).join('')||'<div class="empty">No upcoming sessions.</div>';$$('[data-tstatus]').forEach(b=>b.onclick=async()=>{try{await api('therapist/appointment-status',{method:'POST',body:{id:b.dataset.id,status:b.dataset.tstatus}});await loadSchedule()}catch(x){msg($('#therapist-message'),x.message)}})}catch(x){msg($('#therapist-message'),x.message)}}
 async function loadAvail(){try{const d=await api('therapist/availability');$('#therapist-availability-list').innerHTML=(d.availability||[]).map(a=>`<div class="patient-card"><strong>${dayNames[a.weekday]}</strong> · ${esc(a.start_time)}–${esc(a.end_time)}</div>`).join('')||'<div class="empty">No availability configured.</div>'}catch(x){msg($('#therapist-message'),x.message)}}
 async function save(e,block){e.preventDefault();const d=formObj(e.target);if(block)d.action='block';try{await api('therapist/availability',{method:'POST',body:d});e.target.reset();await loadAvail();msg($('#therapist-message'),block?'Unavailable time blocked.':'Availability added.','good')}catch(x){msg($('#therapist-message'),x.message)}}
}

if(app==='portal')initPortal();if(app==='admin')initAdmin();if(app==='therapist')initTherapist();
})();
